# Generated by Django 5.0.6 on 2026-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sante", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("MEDECIN", "Médecin"),
                    ("RECEPTIONNISTE", "Réceptionniste"),
                    ("ADMINISTRATEUR", "Administrateur"),
                ],
                max_length=20,
            ),
        ),
    ]
